# workflow 的名称。如果省略该字段，默认为当前 workflow 的文件名。
name: CI

# 触发 workflow 的条件
on:
  push:
    branches: [master]

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # job 名
  build-and-deploy:
    # runs-on字段指定运行所需要的虚拟机环境。它是必填字段。目前可用的虚拟机如下。
    runs-on: ubuntu-latest
    # steps表示执行步骤
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        env:
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm i -g pnpm && npm install && npm run build
