name: CI

# 触发 workflow 的条件
on:
  push:
    branches:
      - master
    # tags:
    #   - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      # - name: Deploy to Current Repo
      #   uses: JamesIves/github-pages-deploy-action@4.0.0
      #   with:
      #     branch: gh-pages
      #     folder: dist

      - name: Deploy to Public Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vacrain/hj
          branch: main
          clean: true
          folder: dist
          single-commit: true
          commit-message: 'Deploy GitHub Pages~'
