# workflow 的名称。如果省略该字段，默认为当前 workflow 的文件名。
name: CI

# 触发 workflow 的条件
on:
  push:
    branches:
      - master
    # tags:
    #   - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
